### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by jsanz**
* Remove unused dependency and added a `start` script
* Serve the index HTML file from the server
* Use Elastcisearch `ES_URL` environment variable if set
* Serve from `PORT` environment variable if set
* Style the form using [picocss](https://picocss.com/)
* Submit when hitting the `Enter` key anywhere

### CODE REVIEW

**Comment by jsanz** [comment]
@thomasneirynck @nreese I've updated this PR with last changes and now the app expects a ES cluster that supports hexgrid.

image


I'd still would like to get some way to populate or suggest entries for the index name and geometry field name inputs, but that would maybe make the code harder to read so let me know if you want me to give a hand on that or better leave it as it is.

**Comment by nreese** [comment]
> I'd still would like to get some way to populate or suggest entries for the index name and geometry field name inputs, but that would maybe make the code harder to read so let me know if you want me to give a hand on that or better leave it as it is.

I would leave that out of this PR.

**Review by nreese — APPROVED** [review]
LGTM. Thanks for hosting file on web server and UI updates

**Comment by thomasneirynck** [comment]
Thx @jsanz !

**Pull request merged**
